### ISSUE TITLE
Dispensers Turning Into Command Blocks

### ISSUE THREAD

**Issue by jjisf** [Nincodedo/mc-java-bedrock-bone-meal-datapack#10]
The second you place a dispenser that isn't facing up or down in a world with the datapack, it will turn into a command block. Occasionally it fails to do so and leaves the dispenser.
It seems like it the only time it won't turn into a command block is when you are right next to where you are placing it and at eye level. (like one block away ).

1. Install the Data pack in a world.
2. Place a dispenser horizontally.
3. See error

![2024-04-13_13 11 46](https://github.com/Nincodedo/mc-java-bedrock-bone-meal-datapack/assets/166953106/5b570010-1ae9-488e-8a53-4efd00cc4b9c)
![2024-04-13_13 11 57](https://github.com/Nincodedo/mc-java-bedrock-bone-meal-datapack/assets/166953106/afc639ea-7e39-4dc0-95cf-5ddea2f12906)
![2024-04-13_13 12 13](https://github.com/Nincodedo/mc-java-bedrock-bone-meal-datapack/assets/166953106/3372efdf-efe8-4d86-90b9-6baca32f9096)

 - OS: Windows 11 Home
 - Version 23H2

**Comment by Nincodedo** [comment]
What version of Minecraft is this?

**Comment by itslilscorp** [comment]
I can confirm the same issue happens for me on a Fabric 1.20.4 server. When a dispenser is placed, it changes into a commandblock with the command `function brbm:dispenser/check_new`.

**Comment by unlikelyvee** [comment]
this just happened to me on my fabric server as well

**Comment by Nincodedo** [comment]
@unlikelyvee open a new issue
