### ISSUE TITLE
Placed dispensers immediately turn into command blocks

### ISSUE THREAD

**Issue by mining-away** [Nincodedo/mc-java-bedrock-bone-meal-datapack#9]
**Describe the bug**
When placing a dispenser, it briefly appears as a dispenser block before turning into a command block.
Placing dispensers very very close (maybe less than one block) to the player results in dispensers being placed without turning into command blocks, avoiding the bug.

Removing this datapack fixes the bug.

This json error appears in the server startup: 
`[20:51:34] [Worker-Main-1/ERROR]: Couldn't parse element predicates:brbm:is/block/dispenser_triggered_with_bone_meal - Not a json array: {"condition":"minecraft:location_check","predicate":{"block":{"blocks":["minecraft:dispenser"],"nbt":"{Items:[{id:\"minecraft:bone_meal\"}]}","state":{"triggered":true}}}}
[20:51:34] [Worker-Main-1/ERROR]: Couldn't parse element predicates:brbm:is/block/dispenser_not_triggered - Not a json array: {"condition":"minecraft:location_check","predicate":{"block":{"blocks":["minecraft:dispenser"],"state":{"triggered":false}}}}`

**Server version**
 - Purpur 1.20.2
 - bedrock bone meal datapack version 1.2.0+1.20

Looks like a really cool pack, thanks for making!

**Comment by Nincodedo** [comment]
This might be a documentation issue on my side... @mining-away in your server.properties, do you have command blocks enabled?

**Comment by mining-away** [comment]
> This might be a documentation issue on my side... @mining-away in your server.properties, do you have command blocks enabled?

No, they are disabled. I see they're necessary; didn't think to check that. Thanks!

**Comment by Nincodedo** [comment]
No problem! I've updated my documentation so others don't run into the same issue.
